apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-ns-echo-api.yaml
  - echo-api-authpolicy-echo-api.yaml
  - echo-api-deployment-echo-api.yaml
  - echo-api-httproute-echo-api.yaml
  - echo-api-ratelimitpolicy-echo-api-rlp.yaml
  - echo-api-service-echo-api.yaml
  - openshift-gitops-job-echo-api-httproute.yaml
