apiVersion: v1
kind: Secret
metadata:
  name: globex-db
  namespace: globex-apim-user1
type: Opaque
stringData:
  database-user: globex
  database-password: globex  # DEMO SECRET - change for production
  database-name: globex
  database-admin-password: globex  # DEMO SECRET - change for production
  database-debezium-password: debezium  # DEMO SECRET - change for production
