apiVersion: v1
kind: ServiceAccount
metadata:
  name: globex-db
  namespace: globex-apim-user1
  labels:
    app: globex-db
    app.kubernetes.io/name: globex-db
    app.kubernetes.io/part-of: globex
