apiVersion: v1
kind: Service
metadata:
  name: globex-mobile
  namespace: globex-apim-user1
  labels:
    app: globex-mobile
    app.kubernetes.io/name: globex-mobile
    app.kubernetes.io/part-of: globex
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: globex-mobile
  type: ClusterIP
