apiVersion: v1
kind: ServiceAccount
metadata:
  name: globex-store-app
  namespace: globex-apim-user1
  labels:
    app: globex-store-app
    app.kubernetes.io/name: globex-store-app
    app.kubernetes.io/part-of: globex
