apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-clusterissuer-prod-web-lets-encrypt.yaml
  - cluster-ns-ingress-gateway.yaml
  - ingress-gateway-authpolicy-prod-web-deny-all.yaml
  - ingress-gateway-gateway-prod-web.yaml
  - ingress-gateway-podmonitor-istio-proxies.yaml
  - ingress-gateway-ratelimitpolicy-prod-web.yaml
  - ingress-gateway-service-prod-web-metrics-proxy.yaml
  - ingress-gateway-servicemonitor-prod-web.yaml
  - ingress-gateway-tlspolicy-prod-web.yaml
  - openshift-gitops-job-aws-credentials.yaml
