apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespace
  - cluster-ns-keycloak.yaml

  # Operator
  - keycloak-operatorgroup.yaml
  - keycloak-subscription-rhbk-operator.yaml

  # Database
  - keycloak-secret-postgres-db.yaml
  - keycloak-secret-keycloak-db-password.yaml
  - keycloak-deployment-postgres-db.yaml
  - keycloak-service-postgres-db.yaml

  # Keycloak instance
  - keycloak-keycloak.yaml

  # Realm import
  - keycloak-keycloakrealmimport-apicurio.yaml
