apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespace
  - cluster-ns-keycloak.yaml

  # RHBK Operator
  - rhbk-operatorgroup.yaml
  - rhbk-subscription-rhbk-operator.yaml

  # PostgreSQL Database
  - rhbk-secret-postgres-db.yaml
  - rhbk-deployment-postgres-db.yaml
  - rhbk-service-postgres-db.yaml

  # Keycloak Instance
  - rhbk-secret-keycloak-db-password.yaml
  - rhbk-keycloak.yaml

  # PostSync Job to patch Keycloak hostname
  - openshift-gitops-job-rhbk-hostname.yaml
