apiVersion: v1
kind: Secret
metadata:
  name: postgres-db
  namespace: rhbk
  labels:
    app.kubernetes.io/name: postgres-db
    app.kubernetes.io/part-of: connectivity-link
type: Opaque
stringData:
  POSTGRES_DATABASE: keycloak
  POSTGRES_EXTERNAL_ADDRESS: postgres-db.rhbk.svc.cluster.local:5432
  POSTGRES_HOST: postgres-db.rhbk.svc.cluster.local
  POSTGRES_PASSWORD: keycloak  # DEMO SECRET - change for production
  POSTGRES_SUPERUSER: "false"
  POSTGRES_USERNAME: keycloak
