apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: keycloak
  labels:
    app: postgres-db
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres-db
  type: ClusterIP
