apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: rhbk
  labels:
    app.kubernetes.io/name: postgres-db
    app.kubernetes.io/part-of: connectivity-link
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgres-db
  type: ClusterIP
