apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-password
  namespace: rhbk
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: connectivity-link
type: Opaque
stringData:
  password: keycloak  # DEMO SECRET - must match postgres-db secret
