apiVersion: v1
kind: Secret
metadata:
  name: postgres-db
  namespace: keycloak
type: Opaque
stringData:
  database-user: keycloak
  database-password: keycloak  # DEMO SECRET - change for production
  database-name: keycloak
