apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhbk-operator
  namespace: rhbk
  labels:
    app.kubernetes.io/name: rhbk-operator
    app.kubernetes.io/part-of: connectivity-link
spec:
  targetNamespaces:
    - rhbk
