apiVersion: v1
kind: Namespace
metadata:
  name: globex-apim-user1
  labels:
    app.kubernetes.io/name: globex-apim-user1
    app.kubernetes.io/part-of: connectivity-link
    argocd.argoproj.io/managed-by: openshift-gitops
