apiVersion: v1
kind: Service
metadata:
  name: echo-api
  namespace: echo-api
  labels:
    app.kubernetes.io/instance: echo-api
    app.kubernetes.io/name: echo-api
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/instance: echo-api
    app.kubernetes.io/name: echo-api
