apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: echo-api
  namespace: echo-api
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: echo-api
  rules:
    authorization:
      allow-all:
        opa:
          rego: "allow = true"
