apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: globex
  labels:
    app.kubernetes.io/name: customer-service
    app.kubernetes.io/instance: globex-user1
spec:
  selector:
    app.kubernetes.io/name: customer-service
    app.kubernetes.io/instance: globex-user1
  ports:
    - port: 8080
