apiVersion: v1
kind: Service
metadata:
  name: catalog-db
  namespace: globex
  labels:
    app.kubernetes.io/name: catalog-db
    app.kubernetes.io/instance: globex-user1
spec:
  selector:
    app.kubernetes.io/name: catalog-db
    app.kubernetes.io/instance: globex-user1
  ports:
    - port: 5432
