apiVersion: apps/v1
kind: Deployment
metadata:
  name: globex-store-app
  namespace: globex
  labels:
    app.kubernetes.io/name: globex-store-app
    app.kubernetes.io/instance: globex-user1
    app.kubernetes.io/version: "latest"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: globex-store-app
      app.kubernetes.io/instance: globex-user1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: globex-store-app
        app.kubernetes.io/instance: globex-user1
    spec:
      serviceAccountName: globex-store-app
      containers:
        - name: globex-store-app
          image: quay.io/laurenttourreau/globex-store:npe-fixed
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: globex-db
                  key: database-user
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: globex-db
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: globex-db
                  key: database-name
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://globex-db:5432/${POSTGRESQL_DATABASE}"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            limits:
              cpu: 200m
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 128Mi
