apiVersion: v1
kind: ServiceAccount
metadata:
  name: globex-mobile
  namespace: globex-apim-user1
  labels:
    app.kubernetes.io/name: globex-mobile
    app.kubernetes.io/instance: globex-user1
    app.kubernetes.io/version: "latest"
