apiVersion: v1
kind: Secret
metadata:
  name: globex-db
  namespace: globex
  labels:
    helm.sh/chart: globex-db-0.1.0
    app.kubernetes.io/name: globex-db
    app.kubernetes.io/instance: globex-user1
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
stringData:
  database-user: globex
  database-password: globex
  database-name: globex
  database-admin-password: adminpassword
  database-debezium-password: dbz
