apiVersion: v1
kind: ServiceAccount
metadata:
  name: globex-db
  namespace: globex
  labels:
    app.kubernetes.io/name: globex-db
    app.kubernetes.io/instance: globex-user1
    app.kubernetes.io/version: "latest"
