apiVersion: v1
kind: Service
metadata:
  name: globex-db
  namespace: globex
  labels:
    app.kubernetes.io/name: globex-db
    app.kubernetes.io/instance: globex-user1
    app.kubernetes.io/version: "latest"
spec:
  ports:
    - port: 5432
      name: postgresql
  selector:
    app.kubernetes.io/name: globex-db
    app.kubernetes.io/instance: globex-user1
