apiVersion: v1
kind: ServiceAccount
metadata:
  name: globex-store-app
  namespace: globex
  labels:
    app.kubernetes.io/name: globex-store-app
    app.kubernetes.io/instance: globex-user1
    app.kubernetes.io/version: "latest"
