apiVersion: kuadrant.io/v1
kind: TLSPolicy
metadata:
  name: prod-web
  namespace: ingress-gateway
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cluster
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: prod-web
