apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: productcatalog
  namespace: ingress-gateway
  labels:
    app.kubernetes.io/name: productcatalog
    app.kubernetes.io/part-of: connectivity-link
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: productcatalog
  limits:
    "productcatalog-limit":
      rates:
        - limit: 20
          window: 10s
