apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prod-web-service-monitor
  namespace: ingress-gateway
spec:
  endpoints:
    - path: /stats/prometheus
      port: metrics
  selector:
    matchLabels:
      istio.io/gateway-name: prod-web
