apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: prod-web-rlp-lowlimits
  namespace: ingress-gateway
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: prod-web
  limits:
    default-limits:
      rates:
      - limit: 5
        window: 10s
