apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Cluster-scoped resources
  - cluster-gatewayclass-istio.yaml
  - cluster-crb-istiod-clusterrole-openshift-gateway-openshift-ingress-openshift-gitops-argocd-application-controller.yaml

  # Namespaces
  - cluster-ns-echo-api.yaml
  - cluster-ns-ingress-gateway.yaml

  # ingress-gateway namespace resources
  - ingress-gateway-tlspolicy-prod-web-tls-policy.yaml

  # openshift-gitops namespace resources (Jobs for dynamic configuration)
  - openshift-gitops-job-globex-ns-delegation.yaml
  - openshift-gitops-job-gateway-prod-web.yaml
