apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ack-system

resources:
  - hostedzone.yaml
  - ns-delegation-job.yaml

commonLabels:
  app.kubernetes.io/name: globex-route53
  app.kubernetes.io/component: dns
  app.kubernetes.io/part-of: connectivity-link
  app.kubernetes.io/managed-by: argocd
