apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: apicurio
spec:
  selector:
    app: postgres-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
